/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package internalpage;

import javax.swing.table.DefaultTableModel;
import java.awt.BasicStroke;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.Border;
import java.awt.Color;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.Vector;

import myApp.reportpage;
/**
 *
 * @author James
 */
public class Reportpage extends javax.swing.JFrame {

    /**
     * Creates new form Reportpage
     */
    public Reportpage() {
        initComponents();
       setLocationRelativeTo(null); 
        
    }
    Border empty = BorderFactory.createEmptyBorder();
    Color hover = new Color(0,255,153);
    Color defbutton = new Color(102,255,102);
    
    void buttonBorderAnimation(JPanel panel){
        
    
    panel.setBackground(hover);
    panel.setBorder(BorderFactory.createLineBorder(Color.BLACK));
    panel.setBorder(BorderFactory.createStrokeBorder(new BasicStroke(2.0f)));
       
    }
 
        
        
        
    
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        rClear = new javax.swing.JButton();
        rAdd = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        days = new javax.swing.JTextField();
        Name = new javax.swing.JTextField();
        hours = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableReport = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 255, 0));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(102, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3), "Employee", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 18))); // NOI18N
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setText("Days of work");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 140, -1));

        rClear.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        rClear.setText("CLEAR");
        rClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rClearActionPerformed(evt);
            }
        });
        jPanel2.add(rClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 90, -1));

        rAdd.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        rAdd.setText("ADD");
        rAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rAddActionPerformed(evt);
            }
        });
        jPanel2.add(rAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 80, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel5.setText("Name");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 140, -1));

        days.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        days.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daysActionPerformed(evt);
            }
        });
        jPanel2.add(days, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 140, -1));

        Name.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jPanel2.add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 140, -1));

        hours.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jPanel2.add(hours, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 140, -1));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel6.setText("Hours of work");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 140, -1));

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 60, 200, 370);

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REPORT");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 190, 60));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/rp-report.png"))); // NOI18N
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 70, 50));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/back button.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 0, 640, 60);

        rDelete.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        rDelete.setText("DELETE");
        rDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(rDelete);
        rDelete.setBounds(220, 60, 90, 26);

        tableReport.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        tableReport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "NAME", "HOURS", "DAYS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableReport);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(200, 90, 440, 340);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rClearActionPerformed
        Name.setText("");
        hours.setText("");
        days.setText("");

    }//GEN-LAST:event_rClearActionPerformed

    private void rAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rAddActionPerformed
        String name = Name.getText();
        String hour = hours.getText();
        String day = days.getText();

        if (name.isEmpty() ||  hour.isEmpty() ||  day.isEmpty()  )
        {
            JOptionPane.showMessageDialog(this,
                "please enter all fields",
                "Try Again",
                JOptionPane.ERROR_MESSAGE);

        }
        else{
            DefaultTableModel model = (DefaultTableModel) tableReport.getModel();
            model.addRow(new Object[]{name,hour,day});

            Name.setText("");
            hours.setText("");
            days.setText("");

        }

    }//GEN-LAST:event_rAddActionPerformed

    private void daysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daysActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_daysActionPerformed

    private void rDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rDeleteActionPerformed
        int row = tableReport.getSelectedRow();

        if (row < 0){
            JOptionPane.showMessageDialog(this,
                "No row is selected! Please select one row",
                "select row",
                JOptionPane.ERROR_MESSAGE);

        }
        else{
            DefaultTableModel model = (DefaultTableModel) tableReport.getModel();
            model.removeRow(row);
        }

    }//GEN-LAST:event_rDeleteActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
       DefaultTableModel model = (DefaultTableModel) tableReport.getModel();
       Vector<Vector> tableData = model.getDataVector();
       
       try{
       FileOutputStream file = new FileOutputStream("file.bin");
       ObjectOutputStream output = new ObjectOutputStream(file);
       
       
       output.writeObject(tableReport);
       
       output.close();
       file.close();}
       catch(Exception ex){
       ex.printStackTrace();
       }
       
       
       
       
       
       
    }//GEN-LAST:event_formWindowClosing

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
     
    }//GEN-LAST:event_formWindowOpened

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
       reportpage  rp = new reportpage ();
        this.dispose();
       rp.setVisible(true);       
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reportpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reportpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reportpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reportpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reportpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Name;
    private javax.swing.JTextField days;
    private javax.swing.JTextField hours;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton rAdd;
    private javax.swing.JButton rClear;
    private javax.swing.JButton rDelete;
    private javax.swing.JTable tableReport;
    // End of variables declaration//GEN-END:variables
}
